### PR TITLE
Better result Screen

### PR DESCRIPTION
**Pull request by sagarkattel**
New Result Screen
new result

### CODE REVIEW

**Comment by sagarkattel** [comment]
How about this one? @salmannotkhan

**Comment by salmannotkhan** [comment]
Did you read the description of issue? It was about adding more information about the test and not decorating current information.

**Comment by sagarkattel** [comment]
Oh sorry my bad

**Comment by sagarkattel** [comment]
But bro you said this one so i tried to make it more visual
salmannotkhan <https://github.com/salmannotkhan> commented on Jan 20
<https://github.com/salmannotkhan/typing-test/issues/4#issue-1108939545>

The current result screen is so dull. It doesn't contain any visual
elements. It would be great to have some visual touch on the result screen,
like a graph or something.

I think chart.js is a good idea for doing it, but I'm open to discussing
other possible solutions.






[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
10/29/22,
11:02:40 PM

**Pull request closed without merging**
