### PR TITLE
Added a new restart button

### PR DESCRIPTION
**Pull request by sagarkattel**
There was no restart button while we were taking the test and in the beginning of the test
So i tried to add the restart button

Changes i have done:

Installed react icons library
-> npm install react-icons --save

Added restart button from react-icons in the Footer.tsx section
->import {VscDebugRestart} from 'react-icons/vsc';

Created span with className as "restart-span" and added a button inside with restart icons from "react-icons"

Make Changes into the Footer.scss file for adding the attributes of newly added span and buttton

### CODE REVIEW

**Comment by sagarkattel** [comment]
restart-button

**Comment by salmannotkhan** [comment]
I don't think restart button is necessary when you can just press Tab to restart the test.

**Comment by sagarkattel** [comment]
But after the typing test starts everything is hidden and people won't know how to restart as Footer is also hidden once timer start. Hope you consider that.

**Comment by salmannotkhan** [comment]
Everything is hidden for a reason. It allows users to focus on the test. [monkeytype](https://www.monkeytype.com) which is inspiration for this project also follows the same approach

**Comment by sagarkattel** [comment]
But brother monkeytype also have restart button right?

**Comment by salmannotkhan** [comment]
It's like that because of personal reason.

**Comment by sagarkattel** [comment]
Okay bro i understand

**Pull request closed without merging**
