### PR TITLE
Added Hacker Theme 💻 

### PR DESCRIPTION
**Pull request by i1s-rishabh**
Hi, Salman - I've added again a new theme called "Hacker" which is inspired from [hackertyper.net](https://hackertyper.net/) so, you can check it out for view how hacker theme will going to look. I've tried it on my system and believe it's looking amazing 🔥 

For the reference of hacker theme i've added two example images below - Hope, you'll like it 👍 

image

image

### CODE REVIEW

**Comment by salmannotkhan** [comment]
Can you please disable your formatter and follow prettier rules?

**Comment by i1s-rishabh** [comment]
> Can you please disable your formatter and follow prettier rules?
> 
> We are following 4 spaces for tabs not 2 spaces tabs

- Hi, Salman
I've changed as per prettier formatter you can check it and merge it!

**Comment by i1s-rishabh** [comment]
@salmannotkhan Bhai if my changes are fine then you can merge it 😄

**Comment by salmannotkhan** [comment]
I didn't get time to review this theme. I'll review it tonight

**Comment by i1s-rishabh** [comment]
> I didn't get time to review this theme. I'll review it tonight

have you reviewed? @salmannotkhan

**Comment by salmannotkhan** [comment]
I liked the hacker theme idea. But currently there is no way to differentiate wrong and right words. We need to work on that

**Comment by salmannotkhan** [comment]
Also do `npm install` before commiting code again I have fixed husky precommit hooks

**Pull request closed without merging**
