### PR TITLE
Option for self-hosting, docker deployment

### PR DESCRIPTION
**Pull request by nooobcoder**
Hi! I am making this small PR to provide users options to self-host your typing-test app. Docker 🐳 will survive for the long run and is a much much better option to run in production. Please check this PR and if you like it let me know.

I am so pumped for future contributions to this project, really liked the tool, awesome work buddy.

I have provided a sample `docker-run` command in the README.md and also a `docker-compose.yaml` file in the root of the repo, whichever the user may find easy.

### CODE REVIEW

**Review by nooobcoder — COMMENTED** [review]
Reviewed merge compatibility, all checks passed.

**Comment by nooobcoder** [comment]
> try to make it one word name. tip: be creative

### I thought of these names,
**Purpleperry, eggplant, shimmering-purple**

What do you feel, I tried to be creative enough with them.

**Comment by salmannotkhan** [comment]
Okay nice idea but I have to take a look into how docker works. So after that only I can merge or suggest some changes.

**Comment by nooobcoder** [comment]
Alright, basically docker is a containerized solution to serve apps in an
isolated environment. Docker simply isolates your host machine by putting
your code into "containers" that are isolated from the core os layer by
software. Docker is a software-based virtualization solution.

You can get started with basics of docker here if you are interested,
https://medium.com/swlh/what-exactly-is-docker-1dd62e1fde38

Thank You

**Comment by nooobcoder** [comment]
Hi @salmannotkhan did you get to know about Docker? Please let me know if any changes are required to be made in the PR. This is one my newest contributions on GitHub and I am learning everyday, please let me know if there is any mistake or you are reviewing someting.

**Comment by salmannotkhan** [comment]
Given commands in README isn't working 
also it's `docker build -t typing-test-app .` not `docker built -t typing-test-app .`

**Comment by salmannotkhan** [comment]
Also I don't think that for serving static file we need docker. correct me if I'm wrong

**Comment by nooobcoder** [comment]
> Given commands in README aren't working
> also it's `docker build -t typing-test-app .` not `docker built -t typing-test-app .`

I would be fixing that in the PR, you said it correctly, the command is **build** and not **built**. Thanks for the correction.



> Also I can't understand why local deployment using docker. can we deploy these images to aws or some cloud?

For this, no such specific answer can be given. Many people love self-hosting apps locally on premises just because docker is fun to use and uses local bandwidth, although this app is not heavy but people would really like if it has a self-hosted solution with Docker. There would not be any harm if you provide Docker builds, it would be +1 instead and watch out for many popular repos, they provide Docker builds, just for the future time, if it becomes popular and people want to self-host it. Docker also provides data security in the context that people are aware that the state of the app is limited in the local premise itself.

You can consider offline cases too, suppose an education institute, they can host your app offline on premise and teach typing test even if they do not have option of internet access.

**Comment by nooobcoder** [comment]
Hi @salmannotkhan please review the commits, I have done my best to fix the mistakes that were previously there, also I have fixed the app URL in your readme file. Let me know if there are still any doubts left.

Have a nice day, bye!

**Review by nooobcoder — COMMENTED** [review]
Reviewed commits

**Comment by salmannotkhan** [comment]
this Dockerfile executes the `npm start` to run the build that will run debug build of our typing-test which could be bad from performance and security perspective.
You have to create a static server using `serve`. it'll will use optimized and secure version of our app

So you have to update Dockerfile and instead of `npm start'
you have to execute 'npm build' first then serve command which can be found [here](https://create-react-app.dev/docs/deployment/#static-server)

**Comment by nooobcoder** [comment]
> this Dockerfile executes the `npm start` to run the build that will run debug build of our typing-test which could be bad from performance and security perspective.
> You have to create a static server using `serve`. it'll will use optimized and secure version of our app
> 
> So you have to update Dockerfile and instead of `npm start'
> you have to execute 'npm build' first then serve command which can be found [here](https://create-react-app.dev/docs/deployment/#static-server)

No issues, I would be creating a Dockerfile separate for production for that too, I would be committing once more with the feature addition.

**Review by nooobcoder — COMMENTED** [review]
Added a production pipeline for Docker. It uses nginx and exposes port 80 to serve static content after building the react-app.

**Comment by nooobcoder** [comment]
Any update for this pull request? C'mon open-source involves collaboration, contribution, this feels bad that after contribution no commits being merged even if they include features. This shall not help you in the long run.

**Comment by salmannotkhan** [comment]
I know and I'm sorry about that but right now I don't have enough time to
verify that nginx is the best option available for docker.
I'll definitely merge this once I get some free time to research on it.

**Comment by salmannotkhan** [comment]
Noone is gonna deploy testing build on docker. So I think it's useless to keep their. only keep production build

**Comment by salmannotkhan** [comment]
and remove extra new lines from readme

**Comment by salmannotkhan** [comment]
Required Changes:
* Remove Test Dockerfile only keep Production one only (because testing is mainly done on local computer not on docker container)
* Make Production Dockerfile well documented like test Dockerfile
* Instead of running `npm install` use `npm ci` (for clean install)
* Instead of copying package.json and package-lock.json use wildcard (package*,json)
* Fix README run command (it's not working)
* Rename theme to eggplant and put it at last in list
* Also update README Theme Contribution snippet according to newly added theme

**Review by salmannotkhan — CHANGES_REQUESTED** [review]
* Make Production Dockerfile well documented like test Dockerfile
* Instead of running `npm install` use `npm ci` (for clean install)
* Instead of copying package.json and package-lock.json use wildcard (package*,json)
* Fix README run command (it's not working)
* Make commit message shorter

**Review by salmannotkhan — CHANGES_REQUESTED** [review]
* Rename theme to "aubergine" (another word for eggplant) and put it at last in list
* Also update README Theme Contribution snippet according to newly added theme
* Update commit message accordingly

**Review by salmannotkhan — CHANGES_REQUESTED** [review]
Remove extra new lines in README. Don't use formattor for readme or else it'll mess up git blame

**Review by salmannotkhan — CHANGES_REQUESTED** [review]
Docker-compose isn't working

**Pull request closed without merging**
