### PR TITLE
Game of Thrones Quotes

### PR DESCRIPTION
**Pull request by ParmarHetul21**

### CODE REVIEW

**Comment by salmannotkhan** [comment]
Please resolve the spacing issues and convert wordlist name to lowercase just so it's matching overall site text.

**Comment by ParmarHetul21** [comment]
@salmannotkhan please check the PR for the changes which you have suggested, I have if there are any more you can suggest thank you.

**Comment by salmannotkhan** [comment]
Please rename the wordlist file also

**Comment by ParmarHetul21** [comment]
renamed the files

**Pull request closed without merging**
