### PR TITLE
Added a theme "Rainbow".

### PR DESCRIPTION
**Pull request by i1s-rishabh**
Added a theme "Rainbow".

### CODE REVIEW

**Comment by i1s-rishabh** [comment]
Please don't forget to mention a lable (HACKTOBERFEST-ACCEPTED) with color code (#9c4668) during merge the PR.
Thank You in Advance

**Comment by salmannotkhan** [comment]
Can you please add screenshots with this theme?

**Comment by i1s-rishabh** [comment]
> Can you please add screenshots with this theme?

Sure,

**Comment by salmannotkhan** [comment]
Can we rename this theme to something that matches the colors?

**Comment by i1s-rishabh** [comment]
> Can we rename this theme to something that matches the colors?

sure

**Comment by i1s-rishabh** [comment]
sorry, my mistake clicked on close PR ... 
and I'm changing the name okay

**Comment by i1s-rishabh** [comment]
changed the theme name rainbow > pink sky

**Comment by i1s-rishabh** [comment]
And Salman bhai, Please don't forget to mention a lable (HACKTOBERFEST-ACCEPTED) with color code (#9c4668) during merge the PR.

**Comment by salmannotkhan** [comment]
Is it working? Because in my local it's not. Theme class in `themes.scss` and theme name in `Header.tsx` should match

**Comment by salmannotkhan** [comment]
The repository already has the hacktoberfest topic so there is no need for any label here

**Comment by i1s-rishabh** [comment]
> The repository already has the hacktoberfest topic so there is no need for any label here

So, Please go ahead and merge it

**Comment by salmannotkhan** [comment]
Please fix the conflicts

**Comment by i1s-rishabh** [comment]
> Please fix the conflicts

Fixed! Now check and let me know

**Comment by salmannotkhan** [comment]
Have are merged properly? If yes can you run prettier on `Header.tsx` which has lot of spacing issues

**Comment by salmannotkhan** [comment]
I have merged this as the spacing issue is not from your side

Thank you for your contribution @i1s-rishabh.

**Pull request merged**
