### PR TITLE
Added theme "Rose-milk"

### PR DESCRIPTION
**Pull request by CleverProgrammerFizan**
Added a new theme called Rose-milk

### CODE REVIEW

**Comment by CleverProgrammerFizan** [comment]
also added a new theme called coffe

**Comment by CleverProgrammerFizan** [comment]
also added a new theme called coffee

**Comment by salmannotkhan** [comment]
Hello Fizan 
Thanks for adding new themes soon I'll test everything and get back to you :)

**Comment by salmannotkhan** [comment]
Great job with themes Fizan but it requires slight changes
- The coffee theme requires some change in `--font-color` it's really hard to read fonts in that color. 
- In Rose theme make `--hl-color` a bit darker so it's easily distinguishable.
- It'll be better if you highlight whole <tr> for incorrect word count instead of just number and leave correct without any styling

P.S.: For coffee theme I'll suggest you switch `--font-color` with `--fg-color` for better visibility

Thanks for contribution

Regards,
Salman Shaikh

**Review by salmannotkhan — CHANGES_REQUESTED** [review]
- Leave Correct words `<tr>` as it is and style the whole Incorrect words `<tr>` instead of just number. remove `.correct` from scss too
- Make `--hl-color` bit more darker so it's easily distinguishable

**Review by salmannotkhan — CHANGES_REQUESTED** [review]
- Use "mocha" as theme name instead of "coffee" it sounds way better
- Fix the commit message
- `--font-color` it's really hard to read fonts in that color.
    
P.S.: For `--font-color` I'll suggest you switch --font-color with --fg-color for better visibility

**Comment by salmannotkhan** [comment]
Thanks for the contribution. Please apply the requested changes so I can merge it

**Comment by salmannotkhan** [comment]
And yes also update the README according to the new theme list :) thanks

**Comment by CleverProgrammerFizan** [comment]
changed everything as requested

**Review by salmannotkhan — APPROVED** [review]
Great!

**Comment by salmannotkhan** [comment]
Great Job Fizan. README is still little messed up but I'll fix that.

Thanks for contributing to the repo

**Pull request merged**
